### PR TITLE
Start the self heal daemon

### PR DESCRIPTION
**Pull request by aravindavk**
- Start one shd per Volume
- Start shd while starting the Replica family volume and
  stop when a Volume is stopped.

Updates: #72
Signed-off-by: Aravinda Vishwanathapura <aravinda@kadalu.io>

### CODE REVIEW

**Comment by aravindavk** [comment]
Shd process starts successfully but heal is not happening.  Replica 2 shd log file

```
[2022-02-08 15:10:46.980291 +0000] I [MSGID: 100030] [glusterfsd.c:2716:main] 0-glusterfs: Started running version [{arg=glusterfs}, {version=2022.01.15}, {cmdlinest
r=glusterfs --volfile-id shd/vol1 -p /var/run/kadalu/shd.vol1.pid -S /var/run/kadalu/shd_shd.vol1.socket -l /var/log/kadalu/shd/shd.vol1.log --xlator-option *replica
te*.node-uuid=76c28fc1-32bc-4d38-82dd-6b7b8012baa8 --fs-display-name kadalu:shd.vol1 -f /var/lib/kadalu/volfiles/shd.vol1.vol}] 
[2022-02-08 15:10:46.980964 +0000] I [glusterfsd.c:2452:daemonize] 0-glusterfs: Pid of current running process is 815
[2022-02-08 15:10:46.984657 +0000] I [socket.c:928:__socket_server_bind] 0-socket.glusterfsd: closing (AF_UNIX) reuse check socket 9
[2022-02-08 15:10:46.986046 +0000] I [io-stats.c:3705:ios_sample_buf_size_configure] 0-glustershd: Configure ios_sample_buf  size is 1024 because ios_sample_interval
 is 0
[2022-02-08 15:10:46.986400 +0000] I [MSGID: 114020] [client.c:2319:notify] 0-vol1-replicate-0-client-0: parent translators are ready, attempting connect on transpor
t [] 
[2022-02-08 15:10:46.987189 +0000] I [MSGID: 114020] [client.c:2319:notify] 0-vol1-replicate-0-client-1: parent translators are ready, attempting connect on transpor
t [] 
Final graph:
+------------------------------------------------------------------------------+
  1: volume vol1-replicate-0-client-0
  2:     type protocol/client
  3:     option transport-type socket
  4:     option node-uuid 76c28fc1-32bc-4d38-82dd-6b7b8012baa8
  5:     option remote-port 49252
  6:     option remote-host kadalu-dev
  7:     option remote-subvolume /exports/vol1/s1
  8: end-volume
  9:  
 10: volume vol1-replicate-0-client-1
 11:     type protocol/client
 12:     option transport-type socket
 13:     option node-uuid 76c28fc1-32bc-4d38-82dd-6b7b8012baa8
 14:     option remote-port 49253
 15:     option remote-host kadalu-dev
 16:     option remote-subvolume /exports/vol1/s2
 17: end-volume
 18:  
 19: volume vol1-replicate-0
 20:     type cluster/replicate
 21:     option node-uuid 76c28fc1-32bc-4d38-82dd-6b7b8012baa8
 22:     option afr-pending-xattr vol1-client-0,vol1-client-1
 23:     option iam-self-heal-daemon yes
 24:     subvolumes vol1-replicate-0-client-0 vol1-replicate-0-client-1
 25: end-volume
26:  
 27: volume glustershd
 28:     type debug/io-stats
 29:     subvolumes vol1-replicate-0
 30: end-volume
 31:  
+------------------------------------------------------------------------------+
[2022-02-08 15:10:46.987633 +0000] I [MSGID: 101190] [event-epoll.c:669:event_dispatch_epoll_worker] 0-epoll: Started thread with index [{index=0}] 
[2022-02-08 15:10:46.987796 +0000] I [MSGID: 101190] [event-epoll.c:669:event_dispatch_epoll_worker] 0-epoll: Started thread with index [{index=1}] 
[2022-02-08 15:10:46.987869 +0000] E [MSGID: 108006] [afr-common.c:6124:__afr_handle_child_down_event] 0-vol1-replicate-0: All subvolumes are down. Going offline unt
il at least one of them comes back up. 
[2022-02-08 15:10:46.988050 +0000] I [MSGID: 114057] [client-handshake.c:1126:select_server_supported_programs] 0-vol1-replicate-0-client-0: Using Program [{Program-
name=GlusterFS 4.x v1}, {Num=1298437}, {Version=400}] 
[2022-02-08 15:10:46.989767 +0000] I [MSGID: 114046] [client-handshake.c:855:client_setvolume_cbk] 0-vol1-replicate-0-client-0: Connected, attached to remote volume 
[{conn-name=vol1-replicate-0-client-0}, {remote_subvol=/exports/vol1/s1}] 
[2022-02-08 15:10:46.989796 +0000] I [MSGID: 108005] [afr-common.c:6046:__afr_handle_child_up_event] 0-vol1-replicate-0: Subvolume 'vol1-replicate-0-client-0' came b
ack up; going online. 
[2022-02-08 15:10:49.988750 +0000] I [MSGID: 114057] [client-handshake.c:1126:select_server_supported_programs] 0-vol1-replicate-0-client-1: Using Program [{Program-
name=GlusterFS 4.x v1}, {Num=1298437}, {Version=400}] 
[2022-02-08 15:10:49.989216 +0000] W [MSGID: 114043] [client-handshake.c:726:client_setvolume_cbk] 0-vol1-replicate-0-client-1: failed to set the volume [{errno=2}, 
{error=No such file or directory}] 
[2022-02-08 15:10:49.989250 +0000] W [MSGID: 114007] [client-handshake.c:751:client_setvolume_cbk] 0-vol1-replicate-0-client-1: failed to get from reply dict [{proce
ss-uuid}, {errno=22}, {error=Invalid argument}] 
[2022-02-08 15:10:49.989290 +0000] E [MSGID: 114044] [client-handshake.c:756:client_setvolume_cbk] 0-vol1-replicate-0-client-1: SETVOLUME on remote-host failed [{rem
ote-error=Brick not found}, {errno=2}, {error=No such file or directory}] 
[2022-02-08 15:10:49.989304 +0000] I [MSGID: 114051] [client-handshake.c:878:client_setvolume_cbk] 0-vol1-replicate-0-client-1: sending CHILD_CONNECTING event [] 
[2022-02-08 15:10:49.989349 +0000] I [socket.c:848:__socket_shutdown] 0-vol1-replicate-0-client-1: intentional socket shutdown(8)
[2022-02-08 15:10:49.989393 +0000] I [MSGID: 114018] [client.c:2227:client_rpc_notify] 0-vol1-replicate-0-client-1: disconnected from client, process will keep tryin
g to connect glusterd until brick's port is available [{conn-name=vol1-replicate-0-client-1}]
```

@amarts any suspect from the volfile and logs?

**Comment by aravindavk** [comment]
Not sure, but a guess. Either custom port is not known to shd daemon or on disconnect port is reset to zero(That is default 24007). When shd and brick both start together, the brick port is not ready and reset to 24007. Shd tries to get port details from Glusterd.

https://github.com/gluster/glusterfs/blob/1405ee7f0721243a2cb16c9ec997dfc59e703313/xlators/protocol/client/src/client.c#L2305

**Comment by amarts** [comment]
@aravindavk https://github.com/gluster/glusterfs/pull/3230 fixes this behavior. Can you confirm by picking the latest `devel` branch for testing?

**Comment by aravindavk** [comment]
> @aravindavk [gluster/glusterfs#3230](https://github.com/gluster/glusterfs/pull/3230) fixes this behavior. Can you confirm by picking the latest `devel` branch for testing?

Working fine and heal is happening now :+1:

**Pull request merged**
