### PR TITLE
Rebalance helper process

### PR DESCRIPTION
**Pull request by aravindavk**
Fix layout:

```
kadalu _rebalance <pool-name>/<volume-name> <storage-unit-path> \
    --volfile-servers <servers> --fix-layout
```

Migrate data:

```
kadalu _rebalance <pool-name>/<volume-name> <storage-unit-path> \
    --volfile-servers <servers> --migrate-data
```

Example:

```
kadalu _rebalance dev/vol1 /exports/vol1 --fix-layout \
    --volfile-servers server1:49252

kadalu _rebalance dev/vol1 /exports/vol1 --migrate-data \
    --volfile-servers server1:49252
```

Signed-off-by: Aravinda Vishwanathapura <aravinda@kadalu.tech>

### CODE REVIEW

**Comment by aravindavk** [comment]
Pending: 

- Write status to a file
- Accept Volume name and Volfile servers so that this process itself can manage the mount

**Comment by aravindavk** [comment]
@vatsa287 updated with fix-layout and migrate-data options. Also added code to mount the volume. Testing is pending, I will update once it is ready to use.

**Comment by vatsa287** [comment]
> 

Awesome.!

**Comment by vatsa287** [comment]
> @vatsa287 updated with fix-layout and migrate-data options. Also added code to mount the volume. Testing is pending, I will update once it is ready to use.

Awesome!

**Review by vatsa287 — APPROVED** [review]

**Pull request merged**
